---
# defaults for configuring the ipmi plugin
# TODO: Determine if there are reasonable defaults for these.
# if not, then add an if defined block to the templates
collectd_plugin_ipmi_username: ""
collectd_plugin_ipmi_password: ""
