os: linux
language: python
git:
  depth: false
addons:
  apt:
    update: true
before_install:
  - sudo apt-get -y install collectd
install:
  - pip install ansible-lint ansible
script:
  - ansible-lint
  - ansible-playbook -i default.inv main.yml --extra-vars "collectd_conf_output_dir=$HOME/collectd.conf.d" --tags="test" && cat $HOME/collectd.conf.d/*
  - collectd -t -C $HOME/collectd.conf
