---
- hosts: collectd_hosts
  roles:
    - collectd_config
  tags: test
  vars:
    collectd_conf_output_dir: "/etc/collectd.conf.d"
    collectd_plugins:
      # - amqp1
      # - ceph
      - connectivity
      - cpu
      - df
      - disk
      - hugepages
      - intel_rdt
      - interface
      # TODO: reenable this when there are reasonable defaults or the template has been updated
      # - ipmi
      - load
      # - logfile
      - memory
      - network
      - ovs_stats
      - processes
      - procevent
      # - python
      - unixsock
      - uptime
      # - virt

- hosts: collectd_hosts
  name: TripleO roles test
  tasks:
    - name: Do some TripleO deploy stage
      import_role:
        name: tripleo_collectd
  tags: tripleo
