---
- hosts: collectd_hosts
  roles:
    - collectd_config
  tags: test
  vars:
    collectd_conf_output_dir: "/etc/collectd.conf.d"
    collectd_plugins:
      # There are some undefined vars in the template that are causing
      # rendering to fail, these will be updated
      # - amqp1
      - ceph
      - connectivity
      - cpu
      - cpufreq
      - cpusleep
      - csv
      - df
      - disk
      - hugepages
      - intel_rdt
      - interface
      # The rendered conf file is not syntactically correct yet
      # - ipmi
      - load
      - logfile
      - memory
      - network
      - ovs_stats
      - processes
      - procevent
      - unixsock
      - uptime
      - uuid
      - virt

- hosts: collectd_hosts
  name: TripleO roles test
  tasks:
    - name: Do some TripleO deploy stage
      import_role:
        name: tripleo_collectd
  tags: tripleo
