---
- hosts: collectd_hosts
  roles:
    - collectd_config
  tags: test
  vars:
    collectd_conf_output_dir: "/etc/collectd.conf.d"
    collectd_plugins:
      # - amqp1
      - ceph
      - connectivity
      - cpu
      - cpufreq
      - cpusleep
      - csv
      - df
      - disk
      - hugepages
      - logfile
      - memory
      - network
      - processes
      - unixsock
      - uptime
      - uuid
      - virt

- hosts: collectd_hosts
  name: TripleO roles test
  tasks:
    - name: Do some TripleO deploy stage
      import_role:
        name: tripleo_collectd
  tags: tripleo
