---

libdir: /usr/share/osp-observability
workdir: /var/lib/osp-observability

openstack_cloud_name: overcloud
prometheus_scrape_interval: "1s"

#sg-vars
sgcore_git_branch: 'jwysogla-udpsocket'
ceilometer_port: '6420'
prometheus_port: '3000'
ceilometer_pipeline_path: '/etc/ceilometer/pipeline.yaml'
