---

- name: Expose created Prometheus agent directories
  ansible.builtin.set_fact:
    prometheus_config_dir: "{{ prometheus_config_basedir }}/etc/prometheus"
    prometheus_data_dir: "{{ prometheus_config_basedir }}/data"

- name: Prepare configuration and data directory for Prometheus agent
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nobody
    mode: '0750'
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Provide Prometheus agent configuration
  ansible.builtin.template:
    owner: root
    group: root
    mode: '0644'
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    src: prometheus.yml.j2

- name: "Create CA cert file for remote write endpoint"
  ansible.builtin.copy:
    dest: "{{ prometheus_config_basedir }}/etc/prometheus/{{ item.key }}_CA.pem"
    owner: nobody
    group: nobody
    mode: '0644'
    content: "{{ item.value.ca_cert }}"
  loop: "{{ prometheus_remote_write | dict2items }}"
