---
- name: Get service facts
  service_facts:

- name: Check if ceilometer service is deployed
  fail:
    msg: Invalid Env, it doesn't contain ceilometer.
  when: ansible_facts.services["tripleo_ceilometer_agent_notification.service"] is not defined

- name: Create ceilometer pipeline.yml file
  template:
    src: ceilometer_pipeline.yml.j2
    dest: "{{ ceilometer_pipeline_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Restart the notification agent .
  command: systemctl restart tripleo_ceilometer_agent_notification.service
  register: ceilometer_notification_output
  changed_when: false

- name: Show restart output
  debug:
    var: ceilometer_notification_output.stdout
