---
# tasks file for test-role
# Tasks to replace the conditions section from THT
# Set up defaults to set bools to false

- debug:
    var: collectd_plugins

- name: "Remove file"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ collectd_conf_output_dir }}/"
    - "{{ collectd_conf_output_dir }}/../collectd.conf"

- name: "Create config dir"
  file:
    path: "{{ collectd_conf_output_dir }}/"
    state: directory

- name: "Create core collectd config"
  template:
    src: collectd.conf.j2
    dest: "{{ collectd_conf_output_dir }}/../collectd.conf"

- name: "Create plugin config files"
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ collectd_conf_output_dir }}/{{ item }}.conf"
  loop: "{{ collectd_plugins }}"
