---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Some required external params
      set_fact:
        prometheus_config_dir: /etc/prometheus

    - name: "Check that prometheus config file exists"
      stat:
        path: "{{ prometheus_config_dir }}/prometheus.yml"
      register: prometheus_yaml
      failed_when:
        - not prometheus_yaml.stat.exists

    - name: "Get the configuration"
      slurp:
        path: "{{ prometheus_config_dir }}/prometheus.yml"
      register: prometheus_config

    - name: "Check for well-formed config file (HINT: podman exec -it instance cat /etc/prometheus/prometheus.yml)"
      shell: "cat {{ prometheus_config_dir }}/prometheus.yml && yamllint -d '{rules: {line-length: {max: 100} } }' {{ prometheus_config_dir }}/prometheus.yml"
      changed_when: False

    - name: "Sanity check the contents of the config file"
      assert:
        that:
          - '"scrape_interval: 1s" in prometheus_config.content | b64decode'
        fail_msg: "Incorrect contents in prometheus.yml"
