---
# tasks file for test-role
- name: "Print out the params"
  debug:
    var: hostvars[inventory_hostname]

- name: "Print role_vars"
  debug:
    var: role_vars

- name: "Remove file"
  file:
    path: /home/cloud-user/test-file
    state: absent

- name: "Add a file to the target node"
  file:
    path: /home/cloud-user/test-file
    state: touch
    mode: u=rw,g=r,o=r

- name: "Copy config vars into file"
  copy:
    content: "{{role_vars}}"
    dest: /home/cloud-user/test-file

- name: "put other vars into a file"
  shell: |
    echo "collectd_vars: {{ collectd_vars }} " >> /home/cloud-user/test-file
