---
- when:
    - step|int == 0
    - release == 'rocky'
  block:
    - name: Check if collectd.service is deployed
      command: systemctl is-enabled --quiet collectd.service
      failed_when: false
      register: collectd_enabled_result
    - name: Set fact collectd_enabled
      set_fact:
        collectd_enabled: "{{ collectd_enabled_result.rc == 0 }}"
- name: Stop collectd service
  service: name=collectd.service state=stopped enabled=no
  when:
    - step|int == 1
    - release == 'rocky'
    - collectd_enabled|bool
